---
reviewers:
  # The default reviewers
  defaults:
    - repository-owners # group

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    repository-owners:
      - voltgizerz
    general:
      - voltgizerz


files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  "**":
    - repository-owners # group

  "./internal":
    - repository-owners # group

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 4